src/Form/IconType.php
<?php

namespace BasicBuilder\Bundle\EasyBuilderBundle\Form;

use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;


class IconType extends AbstractType
{
    /**
     * @return null|string|\Symfony\Component\Form\FormTypeInterface
     */
    public function getParent()
    {
        return FileType::class;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
            $data = $event->getData();
            $form = $event->getForm();
            if($data && $form->getParent() && $form->getParent()->getData()) {
//                $form->getParent()->getData()->setFile($data);
                $form->getParent()->getData()->uploadFile();
            }
        })
            ;
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['is_admin'] = $options['is_admin'];
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'icon_type';
    }

    public function getBlockPrefix()
    {
        return 'icon_type';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults( array(
            'belongs_to'=>false,
            'is_admin'=>false,
            'required'=>false
        ));
    }
}

src/Resources/views/base_dir/article_header/article_header_v1.html.twig
<section class="main_section">
    <div class="bgImage">
        {% if subMenu.image is not null %}
            <img src="{{ asset(subMenu.image.downloadLink)| imagine_filter('home_slider') }}" alt="{{ article.name }}">
        {% endif %}
    </div>

    <div class="single_image"
         style="background-image: url({{ subMenu.image is not null ? asset(subMenu.image.downloadLink)|imagine_filter('home_slider') : '' }})">
        <div class="single_text">
            <h3>{{ article.title }}</h3>
            <p>{{ article.shortdescription }}</p>
        </div>
    </div>
</section>